### ISSUE TITLE
Call video not working in instgram

### ISSUE THREAD

**Issue by fmehdi1** [vayu-evergarden/bug_tracker_lavender#1]
[logs-2020-06-07-13-43-57.zip](https://github.com/lavender-evergarden/bug_tracker_lavender/files/4774900/logs-2020-06-07-13-43-57.zip)
Rom Name : PE plus
Build Date : 06/06/2010
Rooted or Unrooted : ROOTED
Custom Kernel or Stock Kernel : NOT KERNEL
Steps to reproduce the problem : video call not working in instgram app
Logcat : attached

**Comment by silvanurromadhoni** [comment]
👍
