### ISSUE TITLE
Earphone's microphone issue in video recording apps(gcam,insta,snap)

### ISSUE THREAD

**Issue by ddash69** [vayu-evergarden/bug_tracker_lavender#10]
Rom Name :PixelExperience_Plus_lavender-10.0-20200606-0327-OFFICIAL.zip
Build Date :June 6, 2020 03:27 UTC
Rooted or Unrooted :Unrooted
Custom Kernel or Stock Kernel :stock
Steps to reproduce the problem :connect earphones then record videos through instagram and snapchat and whatsapp(no audio recorded) and in gcam, audio is recorded through phones bottom mike.
Any magisk modules ? :none
Logcat :none

**Comment by fahamx** [comment]
there is only one mic for lavender which is at the bottom . Idk what you are talking about .

**Comment by etahamad** [comment]
Swipe down, switch it.
![Screenshot_20200825-091838582](https://user-images.githubusercontent.com/53538887/91144242-06c07780-e6b4-11ea-8a23-1f9602062436.jpg)
