### ISSUE TITLE
Hide Notch Overlay's Corner Doesn't match with the corner of the phone

### ISSUE THREAD

**Issue by Fr1ction** [vayu-evergarden/bug_tracker_lavender#11]
Rom Name : Pixel Experience OFFICIAL
Build Date : 2020 06 06
Rooted or Unrooted : Rooted with Magisk
Custom Kernel or Stock Kernel : Using Custom Kernel (Predator Kernel)
Steps to reproduce the problem : Changing Notch Behaviour On Display Settings to Hidden
Any magisk modules ? : No
Logcat :
https://hastebin.com/rogugapuxo.pl

**Comment by fahamx** [comment]
OK , thanks :)

Edit : I found it gets installed on default so ill put it to open
