### ISSUE TITLE
Cast screen not working

### ISSUE THREAD

**Issue by Sidhuklien** [vayu-evergarden/bug_tracker_lavender#13]
Rom Name : Pixel Experience plus
Build Date :2020/06/06
Rooted or Unrooted : Rooted with magisk
Custom Kernel or Stock Kernel : Custom predator eas 3.3
Steps to reproduce the problem : By turning on the cast screen
Any magisk modules ? : in screen shot below
Logcat 

  #![Screenshot_20200701-151329994](https://user-images.githubusercontent.com/67649555/86214230-797a0e80-bbad-11ea-9969-a4251d2898bd.jpg)

Logcat

>https://drive.google.com/file/d/12asxTeYGbpLfU40U-SV6uojWCYAa9KX0/view?usp=drivesdk

**Comment by Sidhuklien** [comment]
07-02 14:07:22.137 I/CastMirroringProvider(2910): onDiscoveryModeChanged, mode=0
07-02 14:07:22.138 I/CastMirroringProvider(2910): onDiscoveryModeChanged removing all remote displays



I found it in log while opening cast screen might help you brother

**Comment by fahamx** [comment]
try without any mods and lemme know

**Comment by Sidhuklien** [comment]
Still the same brother. Not working even without modules.

**Comment by Sap1k** [comment]
Can confirm this indeed happens. The connection gets established, but the output is wrong
Here's a photo :)
![IMG_20200806_142124_tigr](https://user-images.githubusercontent.com/27217421/89531608-cb3b3780-d7f0-11ea-8770-f7315a34b02e.jpg)
Logs are here: https://drive.google.com/folderview?id=1GFXkJ9xMpMFro-XjBPXAenF2sHCAFMVP , one is filtered for Wfd, the other isn't
I'll take a look myself tommorow, but might as well leave the log here :)

**Comment by fahamx** [comment]
I am myself not facing it currently , but this issue was there even before too. I don't understand how it came up once again even though it was fixed long time ago. I will look into it.
