### ISSUE TITLE
Automatically locks screen

### ISSUE THREAD

**Issue by Grv-Singh** [vayu-evergarden/bug_tracker_lavender#14]
In various instances even when running moderately demanding processes (think of 480p Youtube Video on default app), the device locks itself, goes to the lock screen but screen light stays put. Probably issue of low RAM, lavender with 3GB here!

**Comment by Grv-Singh** [comment]
Will be updating with Logs, as and when I get hold of them.

**Comment by fahamx** [comment]
Looking forward
