### ISSUE TITLE
cant connect  if  ssid of wifi is hidden always not in range

### ISSUE THREAD

**Issue by yoyoyvillame** [vayu-evergarden/bug_tracker_lavender#17]
Pixel Plus 
 july 5 2020
rooted
predator kernel 7.9
 magisk module is CTS fix

**Comment by etahamad** [comment]
The new API of wifi connection requires to broadcast the wifi ssid and the password.
Btw, just enable Hidden Wifi as screenshot.
![Screenshot_20200820-205545387](https://user-images.githubusercontent.com/53538887/90813301-b221a300-e327-11ea-9203-2b9b24e855c5.jpg)
