### ISSUE TITLE
Screen recording lags

### ISSUE THREAD

**Issue by ufgf** [vayu-evergarden/bug_tracker_lavender#19]
1. crDroid 6.8
2. 08/07/2020
3. Magisk v20.4
4. Stock: 4.4.229-OniiChanKernel-Faham-X-10.0+
#2 Wed Jul 8 15:24:49 UTC 2020
5. Just start recording video with https://play.google.com/store/apps/details?id=com.kimcy929.screenrecorder or any other
6. Audio Compatibility Patch;  Built-In BusyBox (https://4pda.ru/forum/index.php?showtopic=915158&view=findpost&p=92627380);  Energized Protection;  Fullscreen Gestures;  Google Sans Plus Font (https://t.me/AndroidRepo/2630);  Systemless Hosts;  ViPER4Android FX v2.7.1.6
7. Logs: https://www.dl.dropboxusercontent.com/s/w9p321p61shzw9n/logs-2020-07-16-19-11-08.zip

Video example: https://www.dl.dropboxusercontent.com/s/0m2l14poooyyx2b/2020_07_16_18_28_11.mp4

**Comment by fahamx** [comment]
It's normal to have some lag in our device . But I feel that it's better by a lot than previously it was . I will still see if it can be made better.
