### ISSUE TITLE
high volume for calls

### ISSUE THREAD

**Issue by 0cool-f** [vayu-evergarden/bug_tracker_lavender#2]
Rom Name : PE plus
Build Date : 06/06/2020 (even last 3 build)
Rooted or Unrooted : rooted
Custom Kernel or Stock Kernel : predator 7.5 (even stock)
Steps to reproduce the problem : call someone
Logcat : none

when i call someone volume is too high, event at minimum level, i have to use headphones

**Comment by fahamx** [comment]
Can't really help with that . It doesn't seem too high for me or anyone . You can manually lessen the volume if  you research a little

**Comment by fdigiorgio** [comment]
ok, I have two questions about this:
- is this possible to achieve without losing ota feature?
- do I have to do it at every update?

if possible can you give me some tips/link you consider useful to do it by myself?
thankyou

**Comment by 0cool-f** [comment]
Hi @faham1997 ,
I've managed to solve this issue and I want to share the method I used for it: just make a call, use speakerphone, lower speakerphone volume, not to minimum (at minimum value it resets, dunno why), one step above it's sufficient, disable speakerphone and adjust call's volume, that's all.
