### ISSUE TITLE
Recorder issue

### ISSUE THREAD

**Issue by DuyBuck** [vayu-evergarden/bug_tracker_lavender#21]
-Rom name : Pixel Experience plus
-Build date : 30/7/2020
-Unrooted
-Default kernel of the rom
- No masik
+ I want to use the recorder but it didnt recognize my voice (it does not recording any of sound at all) , but those other like Messenger, translate app.... still working very normal...

**Comment by etahamad** [comment]
Uninstall the upp updates, it will work.
