### ISSUE TITLE
GPS not working without WiFi or Mobile signal coverage

### ISSUE THREAD

**Issue by hernan-fernandez** [vayu-evergarden/bug_tracker_lavender#3]
Rom Name : PE
Build Date : 06/06/2020 (even previous builds)
Rooted or Unrooted : unrooted
Custom Kernel or Stock Kernel : Stock kernel
Steps to reproduce the problem : use gpstest app without sim card or WiFi
Logcat : none

The current gps.conf seems to be generating issues when there's not Internet connection, hence there is not a-gps

I have been testing the following successfully

[gps.conf.txt](https://github.com/lavender-evergarden/bug_tracker_lavender/files/4775181/gps.conf.txt)

**Comment by fahamx** [comment]
Do you mean the one u sent works?

**Comment by hernan-fernandez** [comment]
Yes

**Comment by fahamx** [comment]
ok thanks . It has been Fixed
