### ISSUE TITLE
2 issues for now related to Hotspot, Netflix

### ISSUE THREAD

**Issue by utkaldask1** [vayu-evergarden/bug_tracker_lavender#31]
Rom Name : PixelExperience_lavender-11.0-20201129-0411-BETA-OFFICIAL
Build Date :29-11-2020
Rooted or Unrooted : unrooted
Custom Kernel or Stock Kernel : stock
Steps to reproduce the problem : First: Noone can't connect to my hotspot. Even after typing the right password can't connect to my hotspot.
Second: I can't see the videos in netflix. sound is as original as it can get and all I can see is black screen. Subtitles are there, all netflix functions are there but no video is showing up.
I was in pe+ 10 version and all was working fine 
Any magisk modules ? : No
Logcat : https://del.dog/erfehingig

**Comment by fahamx** [comment]
Hotspot Fixed and Netflix might not be working
