### ISSUE TITLE
App crashing

### ISSUE THREAD

**Issue by kaellego** [vayu-evergarden/bug_tracker_lavender#33]
- Rom Name : RD1A.201105.003.C1 PixelExperience_lavender-11.0-20201129-0411-BETA-OFFICIAL
- Build Date : November 29, 2020 04:11 UTC
- Rooted or Unrooted : Unrooted
- Custom Kernel or Stock Kernel : stock 
- Steps to reproduce the problem : Occasionally apps crash, the system freezes. Apps stop working.
- Any magisk modules ? : no
- Logcat : [logcat.log](https://del.dog/raw/exicyleded)

**Comment by fahamx** [comment]
Fixed
