### ISSUE TITLE
Wireless display

### ISSUE THREAD

**Issue by ilijaivanov** [vayu-evergarden/bug_tracker_lavender#34]
Rom Name : PE 11 Beta
Build Date : 2020/12/23
Rooted or Unrooted : Unrooted
Custom Kernel or Stock Kernel : Stock
Steps to reproduce the problem : Go into connected devices -> Cast -> Enable wireless display and then try to connect to a wireless display. It will say "connecting", and then abruptly stop doing anything.
Any magisk modules ? : No
Logcat : https://hastebin.com/raw/unuqefebah

**Comment by fahamx** [comment]
Try on latest version?
