### ISSUE TITLE
Google measure app and maps failed

### ISSUE THREAD

**Issue by ghost** [vayu-evergarden/bug_tracker_lavender#35]
Rom Name : PixelExperience_lavender-11.0-20201223-1803-BETA-OFFICIAL
Build Date : 2020/12/23
Rooted or Unrooted : Unrooted
Custom Kernel or Stock Kernel : Stock
Steps to reproduce the problem : open measure app or calibrate maps with live view
Any magisk modules ? : nope
Logcat : https://hastebin.com/daxuxanita.sql

**Comment by ghost** [comment]
Any question sir?

**Comment by fahamx** [comment]
Looking into it
