### ISSUE TITLE
No. of columns in Quick Settings

### ISSUE THREAD

**Issue by ghost** [vayu-evergarden/bug_tracker_lavender#36]
In stock pixel phones, the default no. of rows is 2 for portrait orientation and for landscape it's 1. Whereas in rom it's 3 rows and 2 rows for portrait and landscape respectively. (Reporting this as it's not pe+ build where we get option to change these, there is no logs for this.)

Stock kernel.
Rooted with magisk 21.4.
Build date: 21 Jan, 2021

**Comment by fahamx** [comment]
this is not a bug
