### ISSUE TITLE
widevine L1

### ISSUE THREAD

**Issue by hernan-fernandez** [vayu-evergarden/bug_tracker_lavender#4]
Rom Name : PE
Build Date : 06/06/2020 (even previous builds)
Rooted or Unrooted : unrooted
Custom Kernel or Stock Kernel : Stock kernel
Steps to reproduce the problem : use drminfo to check widevine level
Logcat : none

Copy lib and lib64 folders from DRM-L1-Jan--patch.zip to support widevine L1 without magisk

**Comment by fahamx** [comment]
L1 is not officially supported .
But you can enable it by flashing L1 patch after turning the kernel to permissive.
