### ISSUE TITLE
OTG

### ISSUE THREAD

**Issue by BRANT-bruno** [vayu-evergarden/bug_tracker_lavender#40]
Rom Name : PE A11
    Build Date : 21012021
    Rooted or Unrooted : Rooted
    Custom Kernel or Stock Kernel : Stock Kernel
    Steps to reproduce the problem : Plugin a pendrive on otg adapter
    Any magisk modules ? : busybox for android ndk; full screen/immersive gestures; google sans plus font.
    Logcat : https://drive.google.com/file/d/10n6d7ykq3oNPgZANtrICgY_Ixzcm7f7m/view?usp=sharing

**Comment by fahamx** [comment]
Will look into it
