### ISSUE TITLE
Hotspot error

### ISSUE THREAD

**Issue by Tanishq2266** [vayu-evergarden/bug_tracker_lavender#42]
Pixel experience plus 10,th March first build
Redmi Note 7
Rooted
No modules installed
No custom kernels
Don't know how to reproduce but u can try on of wifi and Hotspot together it happens sometimes btw I'm attaching a log 
[logs-2021-03-11-18-40-59.zip](https://github.com/lavender-evergarden/bug_tracker_lavender/files/6123202/logs-2021-03-11-18-40-59.zip)

**Comment by fahamx** [comment]
Invalid
