### ISSUE TITLE
Screenshot issue

### ISSUE THREAD

**Issue by Tanishq2266** [vayu-evergarden/bug_tracker_lavender#45]
I faced this oftenly that I have enabled 3 fi her screenshot and sometimes when I use 3 finger screenshot it doesn't take screenshot normally it takes partial screenshot and ask me to select area to take screenshot 
I don't know why it's happening though I am not clicking volume up while taking ss the shortcut for taking partial screenshot please see this issue and for making this issue ok I have to reboot it

**Comment by fahamx** [comment]
Invalid no logs. Working fine
