### ISSUE TITLE
Google Assistant Hot Word Detection ("Ok Google")

### ISSUE THREAD

**Issue by cicadap5** [vayu-evergarden/bug_tracker_lavender#47]
Rom name: Pixel Experience Plus
Build date: March 10, 2021 (latest initial release for Plus edition)
Rooted: Latest Magisk 22.0
Stock kernel: Predator EAS 4.3 (Same with Stock kernel)
Steps to reproduce: Go to assistant setting /voice match/turn on "ok google"/then go to voice model/ you can retrain voice model. After that after "Ok Google" is detected, the assistant should wake up but it doesn't happen.  I have attached video for your reference. (Please do check)
I guess hot word detection blobs are remaining to be added.
No magisk module installed 
Logcat (not sure if this log captures all the possible log errors about the issue) but i am attaching logs too 
[google_assistsnt.txt](https://github.com/lavender-evergarden/bug_tracker_lavender/files/6136375/google_assistsnt.txt)

https://user-images.githubusercontent.com/80334331/111063855-e385da00-84d6-11eb-8c38-4df692614008.mp4

Video for your reference :

**Comment by fahamx** [comment]
Can't be fixed. Hotword blobs are Google proprietary files for their device. Unless i get my hands on proprietary files for lavender . This cannot be fixed.

**Comment by cicadap5** [comment]
Okay, so a10 blobs won't work? (Cause in a10 it works perfectly fine)

**Comment by fahamx** [comment]
IT doesn't work.A10 blobs
