### ISSUE TITLE
Live Caption button reappears in Volume control after reboot

### ISSUE THREAD

**Issue by cicadap5** [vayu-evergarden/bug_tracker_lavender#48]
Rom name: Pixel Experience Plus
Build date: March 10, 2021 (latest initial release for Plus edition)
Rooted: Latest Magisk 22.0
Stock kernel: Predator EAS 4.3 (Same with Stock kernel)
Steps to reproduce: Go to settings/Sound/Live caption/ Turn off Live caption in volume control/ Reboot device/ this option automatically gets turned on.
Don't know if it's source problem or not
Attaching screenshot:
![Screenshot_20210314-150848_Device_Personalisation_Services](https://user-images.githubusercontent.com/80334331/111063983-9eae7300-84d7-11eb-891f-27baa3eeaec4.png)

**Comment by fahamx** [comment]
Please report this to PE Official group . Bcuz this is not device related and more pixel source related.
