### ISSUE TITLE
Dark theme

### ISSUE THREAD

**Issue by Rootzpower** [vayu-evergarden/bug_tracker_lavender#5]
Rom Name : PE+
Build Date : QQ3A.200605.001
PixelExperience_Plus_lavender-10.0-20200606-0327-OFFICIAL
Rooted or Unrooted : Root
Custom Kernel or Stock Kernel : Stock 
Steps to reproduce the problem : random 
Any magisk modules ? : Busybox, global gps replacer, systemless hosts, advanced Charging Controller.

With last update of PE+ sometimes dark theme don't disable automatic on sunrise. Need to reboot

**Comment by fahamx** [comment]
can't really fix it without logs.

**Comment by Rootzpower** [comment]
What advice would you suggest to produce the error and create log
