### ISSUE TITLE
Random Shutdown

### ISSUE THREAD

**Issue by firstimpressionmusic** [vayu-evergarden/bug_tracker_lavender#51]
Rom Name : PixelExperience_Plus_lavender-11.0-20210419-2112-OFFICIAL
Build Date : Date: April 19, 2021 21:12 UTC
Rooted or Unrooted : Unroot
Custom Kernel or Stock Kernel : Stock
Steps to reproduce the problem : Random shutdown. While youtube vanced, Instagram etc.
Any magisk modules ? : No
Logcat :
[randomshutdown.log](https://github.com/lavender-evergarden/bug_tracker_lavender/files/6369224/randomshutdown.log)

**Comment by ghost** [comment]
It's invalid , not happening with others
