### ISSUE TITLE
No mobile data

### ISSUE THREAD

**Issue by pieterv10** [vayu-evergarden/bug_tracker_lavender#7]
The June update doesn't give me access to mobile data. Tried new APN, but made no difference. This is on ee network in the UK.
Phone is not rooted.

The may ROM has no such issue.

**Comment by twentydeepsteps** [comment]
Need more details man. If possible provide logcat/screenshot. Thx.

**Comment by pieterv10** [comment]
Thanks for your reply.

Sorry, can't provide that info as I am back on the May ROM. Any other info that would be useful?

**Comment by fahamx** [comment]
This issue will be closed since it doesn't fulfill the requirements
