### ISSUE TITLE
Call History Bug (Phone App)

### ISSUE THREAD

**Issue by twentydeepsteps** [vayu-evergarden/bug_tracker_lavender#8]
Rom Name : crDroid 

 Build Date : crDroid v6.7 - Mon, June 8 2020

 Rooted or Unrooted : Rooted

 Custom Kernel or Stock Kernel : Stock Kernel

 Steps to reproduce the problem : After you make a call, it's history do not appear in call history tab, you must relaunch the app to make it showing up. It is happen randomly.

 Any magisk modules? : BusyBox, Energized Protection, Debloater, Wifi  Bonding, YouTube Vanced.

 Logcat : Attached. Tho I'm not quite sure if the log catches anything but atleast I'm trying.

[logs-2020-06-15-20-24-43.zip](https://github.com/lavender-evergarden/bug_tracker_lavender/files/4780569/logs-2020-06-15-20-24-43.zip)

**Comment by Tanmay2k3** [comment]
i don't think this is the issue tracker for crdoid, i think it's strictly for pixel experience

**Comment by fahamx** [comment]
Cant't really help since i don't think its a device issue
