### ISSUE TITLE
FM Radio Not Working

### ISSUE THREAD

**Issue by twentydeepsteps** [vayu-evergarden/bug_tracker_lavender#9]
Rom Name : crDroid 

 Build Date : crDroid v6.7 - Mon, June 8 2020

 Rooted or Unrooted : Rooted

 Custom Kernel or Stock Kernel : Stock Kernel

 Steps to reproduce the problem : Launch the app, it is literally does nothing. Not working.

 Any magisk modules? : BusyBox, Energized Protection, Debloater, Wifi  Bonding, YouTube Vanced.

 Logcat : Attached.

[logs-2020-06-15-20-43-51.zip](https://github.com/lavender-evergarden/bug_tracker_lavender/files/4780589/logs-2020-06-15-20-43-51.zip)

**Comment by fahamx** [comment]
Looking into it . Thanks

**Comment by fahamx** [comment]
Fixed
